### ISSUE TITLE
"Vuoi pagarne il costo?"

### ISSUE THREAD

**Issue by bertolinimarco** [MirkoPesenti/foundryvtt-fabula-ultima-ttjrpg-unoffical#28]
Scheda PG

Quando trascino dal compendio un oggetto dalla lista e mi chiede se voglio pagarne il costo, se premo "No", lo aggiunge comunque sulla scheda.
(non dovrebbe aggiungersi nulla, né scalare Zenit)

**Comment by MirkoPesenti** [comment]
Quel messaggio l'ho creato nel caso non volessi pagare zenit per aggiungerti l'item, ad esempio se è un'oggetto che trovi in giro come loot

**Comment by bertolinimarco** [comment]
@MirkoPesenti Quindi non è "No" il testo del modale, ma "Aggiungi gratis" o "Paga il costo"?
